# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: sonic-mgmt
    type: github
    name: Azure/sonic-mgmt
    endpoint: build

stages:
- stage: Build
  pool: sonicbld
  variables:
    NUM_ASIC: 4
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      buildOptions: 'USERNAME=admin SONIC_BUILD_JOBS=$(nproc) NUM_ASIC=${{ variables.NUM_ASIC }}'
      jobGroups:
      - name: vs

- stage: Test
  variables:
  - name: inventory
    value: veos_vtb
  - name: testbed_file
    value: vtestbed.csv

  jobs:
  - job:
    pool: sonictest
    displayName: "kvmtest-multi-asic-t1-lag"
    timeoutInMinutes: 240

    steps:
    - template: run-test-template.yml
      parameters:
        dut: vlab-08
        tbname: vms-kvm-four-asic-t1-lag
        ptf_name: ptf_vms6-4
        tbtype: multi-asic-t1-lag
